decide to put configuration in PKGBUILD file

diff --git a/lfspkg/lfspkg b/lfspkg/lfspkg
--- a/lfspkg/lfspkg
+++ b/lfspkg/lfspkg
@@ -26,25 +26,94 @@ create_pkg() {
 
     touch $PACKAGE_PATH/$1/control.json
     cat << EOF > $PACKAGE_PATH/$1/control
-[General]
+#!/bin/bash
+# [General]
 
-[Version]
-stable_version=
-version_listing=
-version_scheme=
-latest_version=
+# [Version]
+# stable_version=
+# version_listing=
+# version_scheme=
+# latest_version=
 
-[Build]
-distfiles=
-configure=
-cflags=
-cxxflags=
+# [Build]
+# distfiles=
+# configure=
+# cflags=
+# cxxflags=
 
-[Dependencies]
-depends_on=
-depended_by=
-lock=
+# [Dependencies]
+# depends_on=
+# depended_by=
+# lock=
 EOF
     echo "Created package $1 successfully"
     exit 0
+}
+
+# Retrieve a key from a package
+get_pkg_data() {
+    [ $# -eq 0 ] \
+        && echo "No package name provided" \
+        && exit 1
+
+    [ $# -eq 1 ] \
+        && echo "No configuration option selected" \
+        && exit 1
+
+    [ ! -e $PACKAGE_PATH/$1/PKGBUILD ] \
+        && echo "Could not find package configuration" \
+        && exit 1
+
+    sed -n "s@#\s*$2=\s*\(.*\)\($\)@\1@" $1
+}
+
+# Change a key in a package
+change_pkg_data() {
+    [ $# -eq 0 ] \
+        && echo "No package name provided" \
+        && exit 1
+
+    [ $# -eq 1 ] \
+        && echo "No configuration option selected" \
+        && exit 1
+
+    [ ! -e $PACKAGE_PATH/$1/PKGBUILD ] \
+        && echo "Could not find package configuration" \
+        && exit 1
+
+    sed -i "s@#\s*$2=\(.*\)\($\)@\0$3@" $1
+}
+
+# Add a key to a package
+add_pkg_data() {
+    [ $# -eq 0 ] \
+        && echo "No package name provided" \
+        && exit 1
+
+    [ $# -eq 1 ] \
+        && echo "No configuration option selected" \
+        && exit 1
+
+    [ ! -e $PACKAGE_PATH/$1/PKGBUILD ] \
+        && echo "Could not find package configuration" \
+        && exit 1
+
+    sed -i "s@#\[General\]@\0\n#\ $2=$3@" $1
+}
+
+# Set a key in a package
+set_pkg_data() {
+    [ $# -eq 0 ] \
+        && echo "No package name provided" \
+        && exit 1
+
+    [ $# -eq 1 ] \
+        && echo "No configuration option selected" \
+        && exit 1
+
+    [ -z $(get_pkg_data $1 $2) ] \
+        && add_pkg_data $1 $2 $3 \
+        && exit 1
+
+    change_pkg_data $1 $2 $3
 }
